flowchart LR
  Dev[Developer / CI] --> Build[Firmware build]
  Build --> Firmware[Flashed firmware]
  Build --> arduino[arduino]
  Build --> esp[esp]
  Build --> esp32[esp32]
  Build --> esphome[esphome]
  Build --> freertos[freertos]
  Build --> mbed-os[mbed-os]
  Build --> nuttx[nuttx]
  Build --> platformio[platformio]
  Build --> raspberry-pi-pico-sdk[raspberry-pi-pico-sdk]
  Build --> riot-os[riot-os]
  Firmware --> Board[Board / MCU]
  Board --> GPIO[GPIO / pins]
  Board --> Buses[I2C / SPI / UART / CAN]
  Board --> Network[Wi-Fi / BLE / Ethernet / MQTT / HTTP]
  Board --> Storage[Flash / NVS / filesystem / partitions]
  GPIO --> Peripherals[Sensors / actuators / displays]
